// Generated by Microsoft TypeSpec

import { Widgets, Error } from "../generated/models/all/demo-service.js";

import { HttpContext } from "../generated/helpers/router.js";

import { ReadWidget } from "../generated/models/all/typespec.js";

export class WidgetsImpl implements Widgets<HttpContext> {
  async list(ctx: HttpContext): Promise<ReadWidget[] | Error> {
    return [
      {
        id: "mock-string",
        weight: 42,
        color: "red",
      },
    ];
  }

  async read(ctx: HttpContext, id: string): Promise<ReadWidget | Error> {
    return {
      id: "mock-string",
      weight: 42,
      color: "red",
    };
  }

  async create(
    ctx: HttpContext,
    id: string,
    weight: number,
    color: "red" | "blue",
  ): Promise<ReadWidget | Error> {
    return {
      id: "mock-string",
      weight: 42,
      color: "red",
    };
  }

  async delete(ctx: HttpContext, id: string): Promise<void | Error> {
    return;
  }
}
