// Generated by Microsoft TypeSpec

import { WidgetsCosmosController } from "./controllers/widgets-cosmos.js";

import { createWidgetServiceRouter } from "./generated/http/router.js";

import express from "express";

import morgan from "morgan";

import { addSwaggerUi } from "./swagger-ui.js";

const azureCosmosEndpoint = process.env.AZURE_COSMOS_ENDPOINT;
const azureCosmosDatabase = process.env.AZURE_COSMOS_DATABASE || "WidgetsDb";
const azureCosmosContainer = process.env.AZURE_COSMOS_CONTAINER || "Widgets";


// Validate required configurations
if (!azureCosmosEndpoint) {
  console.error("Error: AZURE_COSMOS_ENDPOINT environment variable is required");
  process.exit(1);
}

const router = createWidgetServiceRouter(
  new WidgetsCosmosController(azureCosmosEndpoint, azureCosmosDatabase, azureCosmosContainer)
);

const PORT = process.env.PORT || 3000;

const app = express();

app.use(morgan("dev"));

const SWAGGER_UI_PATH = process.env.SWAGGER_UI_PATH || "/.api-docs";

addSwaggerUi(SWAGGER_UI_PATH, app);

app.use(router.expressMiddleware);

app.listen(PORT, () => {
  console.log(`Server is running at http://localhost:${PORT}`);
  console.log(
    `API documentation is available at http://localhost:${PORT}${SWAGGER_UI_PATH}`,
  );
});
