// Generated by Microsoft TypeSpec

import { WidgetsImpl } from "./controllers/widgets.js";

import { createDemoServiceRouter } from "./generated/http/router.js";

import { createServer } from "node:http";

const router = createDemoServiceRouter(new WidgetsImpl());

const PORT = process.env.PORT || 3000;

const server = createServer(router.dispatch);

server.listen(PORT, () => {
  console.log(`Server is running at http://localhost:${PORT}`);
});
