// Generated by Microsoft TypeSpec

import swaggerUi from "swagger-ui-express";

import { openApiDocument } from "./generated/http/openapi3.js";

import type express from "express";

export function addSwaggerUi(path: string, app: express.Application) {
  app.use(path, swaggerUi.serve, swaggerUi.setup(openApiDocument));
}
